if: tag IS present AND tag != latest

git:
  depth: false

language: rust

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows

cache: cargo

stages:
  - build
  - deploy

env:
  - BINARY_NAME=mir-${TRAVIS_TAG}-${TRAVIS_OS_NAME}

jobs:
  include:
    - stage: build
      before_script: sed -i "s/version = \"0.0.0\"/version = \"$(VERSION=${TRAVIS_TAG} ./version.sh tags)\"/" Cargo.toml
      script:
        - cargo build --verbose --release
    - stage: deploy
      script:
        - cp target/release/mir ${BINARY_NAME}
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "${BINARY_NAME}"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      env:
        - TRAVIS_TAG=latest
      script:
        - cp target/release/mir ${BINARY_NAME}
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "${BINARY_NAME}"
        skip_cleanup: true
        on:
          tags: true
