if: tag IS present AND tag != latest

git:
  depth: false

language: rust

matrix:
  include:
    - env: BINARY_OUT=target/release/mir BINARY_NAME=mir-${TRAVIS_OS_NAME} VERSION=${TRAVIS_TAG} TRAVIS_TAG=${TRAVIS_TAG}
      os: linux
    - env: BINARY_OUT=target/release/mir BINARY_NAME=mir-${TRAVIS_OS_NAME} VERSION=${TRAVIS_TAG} TRAVIS_TAG=${TRAVIS_TAG}
      os: osx
    - env: BINARY_OUT=target/release/mir.exe BINARY_NAME=mir-${TRAVIS_OS_NAME}.exe VERSION=${TRAVIS_TAG} TRAVIS_TAG=${TRAVIS_TAG}
      os: windows
    - env: BINARY_OUT=target/release/mir BINARY_NAME=mir-${TRAVIS_OS_NAME} VERSION=${TRAVIS_TAG} TRAVIS_TAG=latest
      os: linux
    - env: BINARY_OUT=target/release/mir BINARY_NAME=mir-${TRAVIS_OS_NAME} VERSION=${TRAVIS_TAG} TRAVIS_TAG=latest
      os: osx
    - env: BINARY_OUT=target/release/mir.exe BINARY_NAME=mir-${TRAVIS_OS_NAME}.exe VERSION=${TRAVIS_TAG} TRAVIS_TAG=latest
      os: windows

cache: cargo

before_script: sed -i '' -e "s/version = \"0.0.0\"/version = \"$(./version.sh tags)\"/" Cargo.toml

script:
  - cargo build --verbose --release
  - find .

before_deploy:
  - cp target/release/mir ${BINARY_NAME}
  - find .

deploy:
  script: find .
  provider: releases
  api_key:
    secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
  file: "${BINARY_NAME}"
  skip_cleanup: true
  on:
    tags: true
    rust: stable
