if: tag IS present AND tag != latest

git:
  depth: false

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

cache: cargo

jobs:
  include:
    - stage: build
      os:
        - linux
        - osx
        - windows
      before_script: sed -i "s/version = \"0.0.0\"/version = \"$(VERSION=${TRAVIS_TAG} ./version.sh tags)\"/" Cargo.toml
      script:
        - cargo build --verbose --release
    - stage: deploy
      os:
        - linux
        - osx
        - windows
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "target/release/mir"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      os:
        - linux
        - osx
        - windows
      env:
        - TRAVIS_TAG=latest
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "target/release/mir"
        skip_cleanup: true
        on:
          tags: true
