language: rust

if: tag IS present AND tag != latest

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

cache: cargo

git:
  depth: false
