if: tag IS present AND tag != latest

git:
  depth: false

language: rust

rust: stable

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

cache: cargo

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      before_script: sed -i "s/version = \"0.0.0\"/version = \"$(VERSION=${TRAVIS_TAG} ./version.sh tags)\"/" Cargo.toml
      script:
        - cargo build --verbose --release
    - stage: deploy
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "target/release/mir"
        skip_cleanup: true
        on:
          tags: true
    - stage: deploy
      env:
        - TRAVIS_TAG=latest
      deploy:
        provider: releases
        api_key:
          secure: ${GITHUB_PERSONAL_ACCESS_TOKEN}
        file: "target/release/mir"
        skip_cleanup: true
        on:
          tags: true
